### ISSUE TITLE
Installing MuseLib on a new Mac doesn't work

### ISSUE THREAD

**Issue by DannyBrown** [Godley/Music-Library#318]
Installed lillypond and MuseLib.

MuseLib doesn't open, but fails silently.

Here is a video of the silent failure
![issue](https://cloud.githubusercontent.com/assets/342035/12022371/20b69a2c-ad87-11e5-988a-555bde391daa.gif)

Here is the OS X Console showing issues I think are related to the launch
<img width="1203" alt="screen shot 2015-12-28 at 17 20 40" src="https://cloud.githubusercontent.com/assets/342035/12022404/605f09fc-ad87-11e5-9d3a-304868c00f93.png">

Cheers and good luck

**Comment by Godley** [comment]
Okeydokey, right click on the app file and go view contents. Enter the folder, then macOS, then find the executable named Application. Run it and post a screenshot of the terminal output please

**Comment by DannyBrown** [comment]
Looks like you left an absolute path in your code somewhere :)

<img width="1124" alt="screen shot 2015-12-28 at 18 33 19" src="https://cloud.githubusercontent.com/assets/342035/12023448/7e17cfba-ad91-11e5-9886-ea11d67691bd.png">
